### ISSUE TITLE
Live examples stopped working (muts-needle-plot)

### ISSUE THREAD

**Issue by mpschr** [biojs/biojs#149]
There is suddenly a problem with the live examples of muts-needle-plot and I am not quite sure what it is. There seems to be a problem with the encoding of some special characters within the d3-code.

See here: http://biojs.io/d/muts-needle-plot

Is this a server problem?

The console output:
```
Uncaught SyntaxError: Unexpected token ILLEGAL
d3-svg-legend.js:1 Uncaught ReferenceError: d3 is not defined
muts-needle-plot@0.8.0:655 Uncaught ReferenceError: d3 is not defined
(program):1 Uncaught SecurityError: Blocked a frame with origin "http://workmen.biojs.net" from accessing a frame with origin "http://biojs.io". Protocols, domains, and ports must match.
d3.js:3389 Uncaught SyntaxError: Unexpected token ILLEGAL
d3-svg-legend.js:1 Uncaught ReferenceError: d3 is not defined
muts-needle-plot@0.8.0:655 Uncaught ReferenceError: d3 is not defined
http://biojs.io/d/muts-needle-plot Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by jmvillaveces** [comment]
D3 contains UTF-8 symbols (like π) invalids in non-UTF8 documents. Try to adding the following element to your HTML:

```
<meta http-equiv="content-type" content="text/html; charset=UTF8">
```

**Comment by greenify** [comment]
> Is this a server problem?

Yes indeed. Thanks for reporting!

We use "node-request-caching" to cache the github sources temporary in memory. It turns out that they don't use utf8 buffers, I fixed that and made [pull request to the lib]( https://github.com/matteoagosti/node-request-caching/pull/7).

BTW here is the [source](https://github.com/biojs/registry-workmen/blob/master/routes/snippet.js#L221) for the registry github proxy.

> Try adding the following element to your HTML:

@jmvillaveces: The registry and sniper add the meta charset header automatically and actually one shouldn't need to write HTML at all.

@mpschr: you can also `require` dependencies - you don't need to add everything to the sniper section, e.g. `var _ = require('underscore')`.
Moreover if you really don't want to use `require`, you could use the [`buildJS`](http://edu.biojs.net/details/package_json/) section which will be used instead of `js` at the registry, so e.g.

```
 "buildJS": [
      "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"
    ],
```

**Comment by mpschr** [comment]
Great, thanks for the solution and explanation!
